include: 
  - board: nice_nano_v2
    shield: ngon1_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano_v2
    shield: ngon1_right
  - board: nice_nano_v2
    shield: settings_reset
